### PR TITLE
fix #305: compile out rust-gpu-tools if both cuda and opencl are disabled

### LINKED ISSUE #305: Cannot build from source with FFI_USE_GPU=0
Even with FFI_USE_GPU=0 rust-gpu-tools are compiled and fail (rightfully) with:

error: At least one of the features `cuda` or `opencl` must be enabled.

I guess rust-gpu-tools should be a conditional dependency.

### PR DESCRIPTION
**Pull request by shawnrader**

### CODE REVIEW

File: rust/src/util/api.rs [hunk 1]
```diff
@@ -67,10 +82,13 @@ pub fn init_log_fd(log_fd: libc::c_int) -> repr_c::Box<InitLogFdResponse> {
...
 #[cfg(test)]
 mod tests {
-
+    #[cfg(any(feature = "opencl", feature = "cuda"))]
     use crate::util::api::get_gpu_devices;
+
+    #[cfg(any(feature = "opencl", feature = "cuda"))]
     use crate::util::types::destroy_gpu_device_response;
 
+    #[cfg(any(feature = "opencl", feature = "cuda"))]
```
Comment (vmx) [inline rust/src/util/api.rs:91]: In case you don't want to repeat the feature flags, you can also do the imports directly in the test function. So it would look like:


```rust
    #[cfg(any(feature = "opencl", feature = "cuda"))]
    #[test]
    #[allow(clippy::needless_collect)]
    fn test_get_gpu_devices() {
        use crate::util::api::get_gpu_devices;
        use crate::util::types::destroy_gpu_device_response;

        let resp = get_gpu_devices();
        …
    }
```

File: rust/src/util/api.rs [hunk 2]
```diff
@@ -32,16 +33,30 @@ pub fn init_log_with_file(file: File) -> Option<()> {
     }
 }
 
+// Serialize the GPU device names into a vector
```
Comment (vmx) [inline rust/src/util/api.rs:36]: This could be a doc comment (even if it's a private function) with three leading slashes.

File: rust/src/util/api.rs [hunk 3]
```diff
@@ -32,16 +33,30 @@ pub fn init_log_with_file(file: File) -> Option<()> {
...
+        .collect();
+
+    devices
+}
+
+// Return empty vector for GPU devices if cuda and opencl are disabled
+#[cfg(not(any(feature = "opencl", feature = "cuda")))]
+fn get_gpu_devices_internal() -> Vec<slice_boxed<u8>> {
+    let v: Vec<slice_boxed<u8>> = Vec::new();
+    v
```
Comment (vmx) [inline rust/src/util/api.rs:52]: I should work to just put `Vec::new()` into the function body.

File: rust/src/util/api.rs [hunk 4]
```diff
@@ -32,16 +33,30 @@ pub fn init_log_with_file(file: File) -> Option<()> {
...
+// Serialize the GPU device names into a vector
+#[cfg(any(feature = "opencl", feature = "cuda"))]
+fn get_gpu_devices_internal() -> Vec<slice_boxed<u8>> {
+    let devices = rust_gpu_tools::Device::all();
+    let devices: Vec<_> = devices
+        .into_iter()
+        .map(|d| d.name().into_bytes().into_boxed_slice().into())
+        .collect();
+
+    devices
```
Comment (vmx) [inline rust/src/util/api.rs:45]: The less code version without rebinding the variable would be:

```suggestion
    devices
        .into_iter()
        .map(|d| d.name().into_bytes().into_boxed_slice().into())
        .collect()
```

**Review by vmx — COMMENTED** [review]
The CI failures seem unrelated to this change. Perhaps retriggering CI on master branch would make sense to see if it also happens there.

My inline comments are only about stylistic things, so feel free to ignore them. I just like take code review as a chance to give folks hints about idiomatic Rust/how I'd do things (which doesn't necessarily need to be better).

File: rust/src/util/api.rs (hunk 2 above)
Comment (shawnrader) [reply rust/src/util/api.rs:36]: Originally I had this as a doc comment, but changed it since it was only called internally.  If there preference it to have it as a doc comment I can switch it back.

**Review by cryptonemo — APPROVED** [review]

File: rust/src/util/api.rs (hunk 2 above)
Comment (vmx) [reply rust/src/util/api.rs]: My take on it is: if it really documents the function, why not making it a doc comment even if it's internal.
